import { Document, Schema, model, models } from "mongoose";

export interface IBusinessAd extends Document {
  _id: string;
  title: string;
  companyName: string;
  clientsName: string;
  telephoneNumber: string;
  email: string;
  orderAwarderName: string;
  designation: string;
  // logo?: string[];
  website?: string;
  description: string; // Array of illustration URLs
  imageUrl?: string; // Array of photograph URLs
  imageTitle?: string;
  price: {
    _id: string; // Automatically generated by MongoDB
    productNumber: string;
    pageType: string;
    priceInUsd: string;
    priceInKsh: string;
    description: string;
  };
  createdAtt: Date;
  isFree: boolean;
  organizer: { _id: string; firstName: string; lastName: string };
}

const BusinessAdSchema = new Schema({
  title: { type: String },
  clientsName: { type: String, required: true },
  companyName: { type: String, required: true },
  telephoneNumber: { type: String, required: true },
  email: { type: String, required: true },
  orderAwarderName: { type: String, required: true },
  designation: { type: String, required: true },
  website: { type: String }, //url of their website
  description: { type: String, required: true }, // Array of URLs to company illustrations
  imageUrl: { type: String }, // Array of URLs to suitable
  imageTitle: { type: String },
  price: { type: Schema.Types.ObjectId, ref: "PricingBusiness" },
  createdAtt: { type: Date, default: Date.now },
  isFree: { type: Boolean, default: false },
  organizer: { type: Schema.Types.ObjectId, ref: "User" }, //user that fills in the info
});

const BusinessAd = models?.BusinessAd || model("BusinessAd", BusinessAdSchema);

export default BusinessAd;
