import { Document, Schema, model, models } from "mongoose";

export interface INgoImage extends Document {
  _id: string;
  title?: string;
  imageUrl?: string;
  ngoProfile: {
    _id: string;
    title: string;
    description: string;
    price: {
      _id: string; // Automatically generated by MongoDB
      productNumber: string;
      pageType: string;
      priceInUsd: string;
      priceInKsh: string;
      description: string;
    };
    imageUrl?: string; // Array of photo URLs
    imageTitle?: string;
    // for Ngo
    name: string;
    physicalAddress: string;
    postalAddress: string;
    telephoneNumber: string;
    faxNumber?: string;
    email: string;
    website?: string;
    contactPersonName: string;
    contactPersonTitle: string;
    createdAtt: Date;
    isFree: boolean;
    category: { _id: string; name: string };
    organizer: { _id: string; firstName: string; lastName: string };
  };
  organizer: { _id: string; firstName: string; lastName: string };
}

const NgoImageSchema = new Schema({
  title: { type: String },
  imageUrl: { type: String }, // Array of URLs to suitable
  ngoProfile: {
    type: Schema.Types.ObjectId,
    ref: "NgoProfile",
  },
  organizer: { type: Schema.Types.ObjectId, ref: "User" }, //user that fills in the info
});

const NgoImage = models?.NgoImage || model("NgoImage", NgoImageSchema);

export default NgoImage;
