import { Document, Schema, model, models } from "mongoose";

export interface IPricingBusiness extends Document {
  _id: string; // Automatically generated by MongoDB
  productNumber: string;
  pageType: string;
  priceInUsd: string;
  priceInKsh: string;
  description: string;
}

const PricingBusinessSchema = new Schema({
  productNumber: { type: String, required: true },
  pageType: { type: String, required: true },
  priceInUsd: { type: String, required: true },
  priceInKsh: { type: String, required: true },
  description: { type: String, required: true },
});

const PricingBusiness =
  models?.PricingBusiness ||
  model<IPricingBusiness>("PricingBusiness", PricingBusinessSchema);

export default PricingBusiness;

// [
//   {
//     "productNumber": "1",
//     "pageType": "1 page",
//     "priceInUsd": "1859",
//     "priceInKsh": "250000",
//     "description": "Maximize exposure with full-page advertisement for businesses in our ebook."
//   },
//   {
//     "productNumber": "2",
//     "pageType": "1/2 page",
//     "priceInUsd": "1487",
//     "priceInKsh": "200000",
//     "description": "Optimize visibility with half-page advertisement for businesses in our ebook."
//   },
//   {
//     "productNumber": "3",
//     "pageType": "1/4 page",
//     "priceInUsd": "1116",
//     "priceInKsh": "150000",
//     "description": "Increase outreach with quarter-page advertisement for businesses in our ebook."
//   },
//   {
//     "productNumber": "4",
//     "pageType": "Business Card",
//     "priceInUsd": "298",
//     "priceInKsh": "40000",
//     "description": "Enhance presence with business card advertisement in our ebook."
//   },
//   {
//     "productNumber": "5",
//     "pageType": "Both Covers",
//     "priceInUsd": "2230",
//     "priceInKsh": "300000",
//     "description": "Gain prominence with advertisement on both covers of our ebook."
//   },
//   {
//     "productNumber": "6",
//     "pageType": "Front Cover Strip",
//     "priceInUsd": "1116",
//     "priceInKsh": "150000",
//     "description": "Stand out with front cover strip advertisement in our ebook."
//   },
//   {
//     "productNumber": "7",
//     "pageType": "Cluster Advert",
//     "priceInUsd": "372",
//     "priceInKsh": "50000",
//     "description": "Maximize impact with cluster advertisement in our ebook."
//   }
// ]
