import { Document, Schema, model, models } from "mongoose";
export interface IPricingNgo extends Document {
  _id: string; // Automatically generated by MongoDB
  productNumber: string;
  pageType: string;
  priceInUsd: string;
  priceInKsh: string;
  description: string;
}
const PricingNgoSchema = new Schema({
  productNumber: { type: String, required: true },
  pageType: { type: String, required: true },
  priceInUsd: { type: String, required: true },
  priceInKsh: { type: String, required: true },
  description: { type: String, required: true },
});

const PricingNgo = models?.PricingNgo || model("PricingNgo", PricingNgoSchema);

export default PricingNgo;

// [
//   {
//     productNumber: "1",
//     pageType: "1 page",
//     priceInUsd: "448",
//     priceInKsh: "60000",
//     description: "Maximize visibility with full-page advertisement for NGOs.",
//   },
//   {
//     productNumber: "2",
//     pageType: "1/2 page",
//     priceInUsd: "298",
//     priceInKsh: "40000",
//     description: "Optimize exposure with half-page advertisement for NGOs",
//   },
//   {
//     productNumber: "3",
//     pageType: "1/4 page",
//     priceInUsd: "223",
//     priceInKsh: "30000",
//     description: "Increase outreach with quarter-page advertisement for NGOs.",
//   },
// ];
